# Generated by Django 5.0.14 on 2025-10-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_access_request_refactor'),
        ('accounts', '0002_user_pesel'),
        ('accounts', '0004_user_groups'),
    ]

    operations = [
    ]
