# Generated by Django 5.0.14 on 2025-10-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251004_2233'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitymembership',
            name='accounts_entitymembership_unique',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='entitymembership',
            unique_together={('user', 'entity', 'role')},
        ),
    ]
