services:
  backend:
    build:
      context: ./backend
      target: dev
    working_dir: /app
    command: dotnet watch --project /app/UKNF.Backend.csproj run --urls http://0.0.0.0:${BACKEND_PORT:-4000}
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:${BACKEND_PORT:-4000}
      PORT: ${BACKEND_PORT:-4000}
      DOTNET_USE_POLLING_FILE_WATCHER: 1
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      target: dev
    working_dir: /app
    command: npm run dev -- --hostname 0.0.0.0 --port ${FRONTEND_PORT:-3000}
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000/api}
      PORT: ${FRONTEND_PORT:-3000}
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
      - frontend-next-cache:/app/.next

volumes:
  frontend-node-modules:
  frontend-next-cache:
