services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: uknf
      POSTGRES_USER: uknf
      POSTGRES_PASSWORD: uknf
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uknf"]
      interval: 5s
      timeout: 5s
      retries: 12

  backend:
    build:
      context: ./backend
      target: dev
    env_file:
      - backend/.env.example
      - .env
    environment:
      DATABASE_URL: postgres://uknf:uknf@db:5432/uknf
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: dev
    command: sh -c "cp -r /opt/node_modules/. /app/node_modules 2>/dev/null || true && npm run dev"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  frontend_node_modules:
