services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: uknf
      POSTGRES_USER: uknf
      POSTGRES_PASSWORD: uknf
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uknf"]
      interval: 5s
      timeout: 5s
      retries: 12

  backend:
    build:
      context: ./backend
      target: production
    env_file:
      - backend/.env.example
      - .env
    environment:
      DATABASE_URL: postgres://uknf:uknf@db:5432/uknf
      DJANGO_CORS_ORIGINS: http://localhost:3000,http://localhost:8123
      DJANGO_DEBUG: "true"
    ports:
      - "8123:80"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: production
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8123/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
